import {
    SiAmazonaws,
    SiBitbucket,
    SiConfluence,
    SiCss3,
    SiCypress,
    SiDocker,
    SiFigma,
    SiGithub,
    SiGnubash,
    SiGo,
    SiGrafana,
    SiGulp,
    SiHtml5,
    SiJavascript,
    SiJenkins,
    SiJest,
    SiJira,
    SiJirasoftware,
    SiMongodb,
    SiMysql,
    SiNestjs,
    SiNodedotjs,
    SiPhp,
    SiPostgresql,
    SiRabbitmq,
    SiReact,
    SiSass,
    SiSlack,
    SiStyledcomponents,
    SiTerraform,
    SiTypescript,
    SiUbuntu,
    SiVercel,
    SiWebpack,
    SiWordpress,
    SiZendframework,
} from 'react-icons/si';

export const techs = [
    {
        href: 'https://developer.mozilla.org/pt-BR/docs/Web/HTML',
        icon: SiHtml5,
        alt: 'HTML5',
        color: '#e35a20',
    },
    {
        href: 'https://developer.mozilla.org/pt-BR/docs/Web/CSS',
        icon: SiCss3,
        alt: 'CSS3',
        color: '#57a0e3',
    },
    {
        href: 'https://www.php.net/',
        icon: SiPhp,
        alt: 'PHP',
        color: '#7174ab',
    },
    {
        href: 'https://developer.mozilla.org/pt-BR/docs/Web/JavaScript',
        icon: SiJavascript,
        alt: 'Javascript',
        color: '#ebd41d',
    },
    {
        href: 'https://www.typescriptlang.org/',
        icon: SiTypescript,
        alt: 'Typescript',
        color: '#2e72bd',
    },
    {
        href: 'https://nodejs.dev/',
        icon: SiNodedotjs,
        alt: 'Node.js',
        color: '#89ba3d',
    },
    {
        href: 'https://go.dev/',
        icon: SiGo,
        alt: 'Go lang',
        color: '#65ccd9',
    },
    {
        href: 'https://www.docker.com/',
        icon: SiDocker,
        alt: 'Docker',
        color: '#23aede',
    },
    {
        href: 'https://aws.amazon.com/',
        icon: SiAmazonaws,
        alt: 'Amazon Web Services',
        color: '#f09101',
    },
    {
        href: 'https://www.mysql.com/',
        icon: SiMysql,
        alt: 'MySQL',
        color: '#4f7a98',
    },
    {
        href: 'https://www.postgresql.org/',
        icon: SiPostgresql,
        alt: 'PostgreSQL',
        color: '#2c5c8a',
    },
    {
        href: 'https://www.mongodb.com/',
        icon: SiMongodb,
        alt: 'MongoDB',
        color: '#0ea04c',
    },
    {
        href: 'https://ubuntu.com/download',
        icon: SiUbuntu,
        alt: 'Ubuntu',
        color: '#d44713',
    },
    {
        href: 'https://www.gnu.org/software/bash/',
        icon: SiGnubash,
        alt: 'Shell',
        color: '#f2f3f3',
    },
];

export const tools = [
    {
        href: 'https://reactjs.org/',
        icon: SiGulp,
        alt: 'Gulp',
        color: '#e14a4a',
    },
    {
        href: 'https://sass-lang.com/',
        icon: SiSass,
        alt: 'Sass',
        color: '#c36190',
    },
    {
        href: 'https://jestjs.io/',
        icon: SiJest,
        alt: 'Jest',
        color: '#7e3653',
    },
    {
        href: 'https://www.cypress.io/',
        icon: SiCypress,
        alt: 'Cypress',
        color: '#05c38f',
    },
    {
        href: 'https://webpack.js.org/',
        icon: SiWebpack,
        alt: 'Webpack',
        color: '#88cbec',
    },
    {
        href: 'https://reactjs.org/',
        icon: SiReact,
        alt: 'React',
        color: '#5dcfef',
    },
    {
        href: 'https://vercel.com/',
        icon: SiVercel,
        alt: 'Vercel',
        color: '#f2f3f3',
    },
    {
        href: 'https://nestjs.com/',
        icon: SiNestjs,
        alt: 'Nestjs',
        color: '#d4214b',
    },
    {
        href: 'https://styled-components.com/',
        icon: SiStyledcomponents,
        alt: 'Styled components',
        color: '#d0945a',
    },
    {
        href: 'https://www.rabbitmq.com/',
        icon: SiRabbitmq,
        alt: 'RabbitMQ',
        color: '#e8741e',
    },
    {
        href: 'https://www.terraform.io/',
        icon: SiTerraform,
        alt: 'Terraform',
        color: '#854fbb',
    },
    {
        href: 'https://jenkins.io/',
        icon: SiJenkins,
        alt: 'Jenkins',
        color: '#ffffff',
    },
    {
        href: 'https://framework.zend.com/',
        icon: SiZendframework,
        alt: 'Zend Framework',
        color: '#30ab2e',
    },
    {
        href: 'https://www.wordpress.org/',
        icon: SiWordpress,
        alt: 'Wordpress',
        color: '#ffffff',
    },
];

export const others = [
    {
        href: 'https://jira.software.com/',
        icon: SiJirasoftware,
        alt: 'Jira Software',
        color: '#247df2',
    },
    {
        href: 'https://www.jira.com/',
        icon: SiJira,
        alt: 'Jira',
        color: '#247df2',
    },
    {
        href: 'https://bitbucket.org',
        icon: SiBitbucket,
        alt: 'Bitbucket',
        color: '#247df2',
    },
    {
        href: 'https://confluence.software.com/',
        icon: SiConfluence,
        alt: 'Confluence',
        color: '#247df2',
    },
    {
        href: 'https://www.slack.com/',
        icon: SiSlack,
        alt: 'Slack',
        color: '#f2f3f3',
    },
    {
        href: 'https://www.github.com/jeanmolossi',
        icon: SiGithub,
        alt: 'Github',
        color: '#f2f3f3',
    },
    {
        href: 'https://www.figma.com/',
        icon: SiFigma,
        alt: 'Figma',
        color: '#9a54f2',
    },
    {
        href: 'https://www.grafana.com/',
        icon: SiGrafana,
        alt: 'Grafana',
        color: '#e87d22',
    },
];
