import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic'

const Canvas = dynamic(() => import('@/presentation/components/canvas'), { ssr: false })

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Jean Molossi | Fullstack Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ minHeight: '300vh' }}>
          <h1>Home</h1>
          
          <Canvas />          
      </main>
    </div>
  )
}

export default Home
