name: Next.JS workflow to verify application healthy

on:
    # Runs on pushes targeting the default branch
    push:
        branches: [$default-branch]

    # Allows to manually trigger the workflow
    workflow_dispatch:

concurrency:
    group: nextjs-health-check
    cancel-in-progress: false

jobs:
    build:
        name: Verify application healthy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9.0.6
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - name: Restore pnpm cache
              uses: actions/cache@v4
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: ${{ runner.os }}-pnpm-

            - name: Restore Next cache
              uses: actions/cache@v4
              with:
                  path: apps/web/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
                  restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

            - name: Install dependencies
              run: pnpm install

            - name: Build with Next.js
              run: pnpm build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: nextjs-build-artifacts
                  path: apps/web/.next

    bundle-analyze:
        name: Analyze page bundle sizes and limits
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with:
                  name: nextjs-build-artifacts
                  path: apps/web/.next
            - name: Run pages size analysis
              run: node ./scripts/bundle-analyzer.mjs

    njsscan:
        name: NodeJS scan check
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4
            - name: nodejsscan scan
              id: njsscan
              uses: ajinabraham/njsscan-action@master
              with:
                  args: '.'
